=== rsins/Scratchpad-Java/JavaStandAloneProgramExamplesTrial/src/com/myexample/jaxb/EmployeeXML-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="employees">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="1" ref="employee"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="employee">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="emailid" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="firstname"  minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="middlename"  minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="lastname"  minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
            <xsd:attribute name="employeeid" type="xsd:int" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="emailid" type="xsd:string"/>

    <xsd:element name="firstname" type="xsd:string"/>

    <xsd:element name="middlename" type="xsd:string"/>

    <xsd:element name="lastname" type="xsd:string"/>
</xsd:schema>

=== rsins/Scratchpad-Java/JavaStandAloneProgramExamplesTrial/src/com/myexample/jaxb/Employees_To_Marshal.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EmployeeXML-schema.xsd">
    <employee employeeid="1001">
        <emailid>shk@abc.com</emailid>
        <firstname>Shahrukh</firstname>
        <middlename></middlename>
        <lastname>Khan</lastname>
    </employee>
    <employee employeeid="1005">
        <emailid>kak@abc.com</emailid>
        <firstname>Katrina</firstname>
        <middlename></middlename>
        <lastname>Khaif</lastname>
    </employee>
    <employee employeeid="1008">
        <emailid>sak@abc.com</emailid>
        <firstname>Salman</firstname>
        <middlename></middlename>
        <lastname>Khan</lastname>
    </employee>
    <employee employeeid="1006">
        <emailid>prc@abc.com</emailid>
        <firstname>Pryanka</firstname>
        <middlename></middlename>
        <lastname>Chopra</lastname>
    </employee>
    <employee employeeid="1007">
        <emailid>rir@abc.com</emailid>
        <firstname>Rithik</firstname>
        <middlename></middlename>
        <lastname>Roshan</lastname>
    </employee>
    <employee employeeid="1002">
        <emailid>jot@abc.com</emailid>
        <firstname>John</firstname>
        <middlename>P</middlename>
        <lastname>Travolta</lastname>
    </employee>
    <employee employeeid="1004">
        <emailid>drm@abc.com</emailid>
        <firstname>Drew</firstname>
        <middlename>Barry</middlename>
        <lastname>Moore</lastname>
    </employee>
    <employee employeeid="1003">
        <emailid>jea@abc.com</emailid>
        <firstname>Jessica</firstname>
        <middlename></middlename>
        <lastname>Alba</lastname>
    </employee>
    <employee employeeid="1009">
        <emailid>cat@abc.com</emailid>
        <firstname>Charlize</firstname>
        <middlename></middlename>
        <lastname>Theron</lastname>
    </employee>
    <employee employeeid="1010">
        <emailid>ram@abc.com</emailid>
        <firstname>Rani</firstname>
        <middlename>L</middlename>
        <lastname>Mukharjee</lastname>
    </employee>
</employees>
