=== rsins/Scratchpad-Java/JavaStandAloneProgramExamplesTrial/src/com/myexample/xmlreader/DBConnections_2-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="databases">
	<xs:complexType>
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="database">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="1">
						<xs:element name="auth" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
						<xs:element name="driverClassName" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
						<xs:element name="maxActive" type="xs:integer" minOccurs="1" maxOccurs="1"></xs:element>
						<xs:element name="maxIdle" type="xs:integer" minOccurs="1" maxOccurs="1"></xs:element>
						<xs:element name="maxWait" type="xs:integer" minOccurs="1" maxOccurs="1"></xs:element>
						<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
						<xs:element name="type" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
						<xs:element name="url" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
						<xs:element name="username" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
						<xs:element name="password" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== rsins/Scratchpad-Java/JavaStandAloneProgramExamplesTrial/src/com/myexample/xmlreader/DBConnections_2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="DBConnections_2-transform.xsl"?>

<databases
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="DBConnections_2-schema.xsd">
	<database>
		<auth>Container</auth>
		<driverClassName>org.gjt.mm.mysql.Driver</driverClassName>
		<maxActive>100</maxActive>
		<maxIdle>10</maxIdle>
		<maxWait>10000</maxWait>
		<name>jdbc/datamigration</name>
		<type>javax.sql.DataSource</type>
		<url>jdbc:mysql://myshec55561d:3306/datamigration</url>
		<username>datam</username>
		<password>datam</password>
	</database>
	<database>
		<auth>Container</auth>
		<driverClassName>oracle.jdbc.driver.OracleDriver</driverClassName>
		<maxActive>100</maxActive>
		<maxIdle>10</maxIdle>
		<maxWait>10000</maxWait>
		<name>jdbc/datamigration1</name>
		<type>javax.sql.DataSource</type>
		<url>jdbc:oracle:thin://myshec55561d:3306/datamigration1</url>
		<username>datam</username>
		<password>datam</password>
	</database>
	<database>
		<auth>Container</auth>
		<driverClassName>oracle.jdbc.driver.OracleDriver</driverClassName>
		<maxActive>100</maxActive>
		<maxIdle>10</maxIdle>
		<maxWait>10000</maxWait>
		<name>jdbc/datam_oracle</name>
		<type>javax.sql.DataSource</type>
		<url>jdbc:oracle:thin:@myshec103527d:1521:datam</url>
		<username>datam</username>
		<password>datam</password>
	</database>
	<database>
		<auth>Container</auth>
		<driverClassName>org.gjt.mm.mysql.Driver</driverClassName>
		<maxActive>100</maxActive>
		<maxIdle>10</maxIdle>
		<maxWait>10000</maxWait>
		<name>jdbc/dev1</name>
		<type>javax.sql.DataSource</type>
		<url>jdbc:mysql://qwer:1111/abcd</url>
		<username>qwert12</username>
		<password>qwerty12345</password>
	</database>
	<database>
		<auth>Container</auth>
		<driverClassName>org.gjt.mm.mysql.Driver</driverClassName>
		<maxActive>100</maxActive>
		<maxIdle>10</maxIdle>
		<maxWait>10000</maxWait>
		<name>jdbc/dev2</name>
		<type>javax.sql.DataSource</type>
		<url>jdbc:mysql://asdfasdf:123/asdfasd</url>
		<username>asdfs</username>
		<password>asdf</password>
	</database>
	<database>
		<auth>Container</auth>
		<driverClassName>com.microsoft.jdbc.sqlserver.SQLServerDriver</driverClassName>
		<maxActive>100</maxActive>
		<maxIdle>10</maxIdle>
		<maxWait>10000</maxWait>
		<name>jdbc/dev3</name>
		<type>javax.sql.DataSource</type>
		<url>jdbc:sqlserver://asdfasdf:12312/asdfasdf</url>
		<username>asdf</username>
		<password>asdf</password>
	</database>
</databases>
